---
- hosts: webservers
  become: yes
  become_method: sudo
  become_user: dry
  tasks:
  - name: download file
    get_url:
      url: https://github.com/mngk/zip_file/raw/master/test_file.zip
      dest: /tmp/mng/test_file.zip
    
  - name: stop the tomcat service
    service: name=tomcat state=started
  - name: checking the user
    command: whoami
