---
- hosts: webservers
  gather_facts: no
  #become: true
  become_user: dry
  sudo: yes
  tasks:
  - name: download file
    get_url:
      url: https://github.com/mngk/zip_file/raw/master/test_file.zip
      dest: /tmp/mng/test_file.zip
    
  - name: stop the tomcat service
    service: name=tomcat state=started
